# skyline_long-read-mngs_config_2021-01-22.yml
# Contains reference file paths on skyline HPC for long-read-mngs workflow. Using references derived from 2021-01-22 index generation.
minimap_host_db: "/data/openomics/references/czid-workflows/host_filter/human/2018-02-15-utc-1518652800-unixtime__2018-02-15-utc-1518652800-unixtime/hg38_phiX_rRNA_mito_ERCC.fasta"
minimap_human_db: "/data/openomics/references/czid-workflows/host_filter/human/2018-02-15-utc-1518652800-unixtime__2018-02-15-utc-1518652800-unixtime/hg38_phiX_rRNA_mito_ERCC.fasta"
minimap2_local_db_path: "/data/openomics/references/czid-workflows/ncbi-indexes-prod/2021-01-22/nt"
diamond_local_db_path: "/data/openomics/references/czid-workflows/ncbi-indexes-prod/2021-01-22/nr"
accession2taxid_db: "/data/openomics/references/czid-workflows/ncbi-indexes-prod/2021-01-22/accession2taxid.marisa"
lineage_db: "/data/openomics/references/czid-workflows/ncbi-indexes-prod/2021-01-22/taxid-lineages.marisa"
taxon_blacklist: "/data/openomics/references/czid-workflows/ncbi-indexes-prod/2021-01-22/taxon_ignore_list.txt"
deuterostome_db: "/data/openomics/references/czid-workflows/ncbi-indexes-prod/2021-01-22/deuterostome_taxids.txt"
nt_info_db: "/data/openomics/references/czid-workflows/ncbi-indexes-prod/2021-01-22/nt_info.marisa"
use_taxon_whitelist: false
taxon_whitelist: null
