# skyline_short-read-mngs_config_2024-02-06.yml
# Contains reference file paths on skyline HPC for short-read-mngs workflow. Using references derived from 2024-02-06 index generation.
host_filter.file_ext: fastq
host_filter.host_genome: human
host_filter.bowtie2_index_tar: /data/openomics/references/czid-workflows/host_filter/human_telomere/2023-07-05/host-genome-generation-1/human_telomere.bowtie2.tar
host_filter.hisat2_index_tar: /data/openomics/references/czid-workflows/host_filter/human_telomere/2023-07-05/host-genome-generation-1/human_telomere.hisat2.tar
host_filter.kallisto_idx: /data/openomics/references/czid-workflows/host_filter/human_telomere/2023-07-05/host-genome-generation-1/human_telomere.kallisto.idx
host_filter.human_bowtie2_index_tar: /data/openomics/references/czid-workflows/host_filter/human_telomere/2023-07-05/host-genome-generation-1/human_telomere.bowtie2.tar
host_filter.human_hisat2_index_tar: /data/openomics/references/czid-workflows/host_filter/human_telomere/2023-07-05/host-genome-generation-1/human_telomere.hisat2.tar
host_filter.adapter_fasta: /data/openomics/references/czid-workflows/adapter_sequences/clipDb.fasta
host_filter.max_input_fragments: 150000000
host_filter.max_subsample_fragments: 2000000
host_filter.ercc_index_tar: /data/openomics/references/czid-workflows/host_filter/ercc/20221031/bowtie2_index_tar/ercc.bowtie2.tar
non_host_alignment.accession2taxid_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/accession2taxid.marisa
non_host_alignment.lineage_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/taxid-lineages.marisa
non_host_alignment.taxon_blacklist: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/taxon_ignore_list.txt
non_host_alignment.deuterostome_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/deuterostome_taxids.txt
minimap2_local_db_path: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/nt_compressed_shuffled.fa
diamond_local_db_path: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/nr_compressed_shuffled.fa
diamond_args: "--mid-sensitive"
postprocess.nt_db: s3://czid-public-references/ncbi-indexes-prod/2024-02-06/index-generation-2/nt_compressed_shuffled.fa
postprocess.nt_loc_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/nt_loc.marisa
postprocess.nr_db: s3://czid-public-references/ncbi-indexes-prod/2024-02-06/index-generation-2/nr_compressed_shuffled.fa
postprocess.nr_loc_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/nr_loc.marisa
postprocess.lineage_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/taxid-lineages.marisa
postprocess.accession2taxid_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/accession2taxid.marisa
postprocess.taxon_blacklist: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/taxon_ignore_list.txt
postprocess.deuterostome_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/deuterostome_taxids.txt
experimental.nt_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/nt_compressed_shuffled.fa
experimental.nt_loc_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/nt_loc.marisa
experimental.nt_info_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/nt_info.marisa
experimental.lineage_db: /data/openomics/references/czid-workflows/ncbi-indexes-prod/2024-02-06/taxid-lineages.marisa
experimental.resist_genome_db: /data/openomics/references/czid-workflows/amr/ARGannot_r2.fasta
experimental.resist_genome_bed: /data/openomics/references/czid-workflows/amr/argannot_genome.bed
